apiVersion: trussle.com/v1alpha1
kind: AWSSqsQueue 
metadata:
  name: test
spec:
  queueName: "kube-test"
  region: "eu-west-1"
  attributes:
    DelaySeconds: "20"
    RedrivePolicy: |
      { "deadLetterTargetArn": "arn:aws:sqs:xx-xxxx-x:xxxxxxxxxxx:kube-test-dl", "maxReceiveCount": 20 }
